TIP_LIST = [
"To view all available commands, use the `$help` command."
"Many of my commands feature command flags you can use to modify/extend the capabilities of a given command."
"Not sure what a command does? You can use the `$help` command to learn more about how a command works. Simply use a given command name as an argument with the `$help` command.\nExample: `$help daily` will show you how to use the `$daily` command."
"You can modify my system context to adjust my personality. Each channel has a unique system context message, which means you can adjust my personality differently for each channel.\nUse `$view_context` to view my current system context message for this channel.\nUse `$set_context` to overwrite my current system context message with a new one.\nUse `$add_context` to add additional content to my current system context message."
"Whenever you send a message that includes my name, I will generate and send a response using my LLM. If you would like to use the LLM to generate a response without using my name, you can use the `$prompt` command."
"Are you sick of me replying to your messages without being prompted? Use the `$ignore` command to stop me from replying to your messages unless you prompt me. Additionally, you can use the `-c` command flag to prevent me from replying to any unprompted messages in a given channel."
"Want to hear my voice? You can command me to join your voice channel using the `$join` command. Once inside of your voice channel, I will read aloud any LLM responses generated as well as any one-line respones generated using the \"#\" character. Once you've grown tired of me, simply use the `$leave` command and I will exit your voice channel. Alternatively, if I detect I am the only user within a voice channel, I will exit the channel myself."
"Did you know I have text-to-speach capabilities? Simply use the `$say` command, and I will read aloud any message to your voice channel."
"Is your channel dead? Want me to send a daily message to your channel? Use the `$daily` command to instruct me to send comics, jokes, facts, and more to your channel once a day."
"Are you bored? Play a game of Wordle with me! Use the `$wordle` command to begin a new game."
"Want help collecting and randomly chosing text-based items? Use my suite of \"Hat-based Collection\" commands.\nUse the `$list` command to view all active hats in this server.\nUse the `$add` command to add an item to a hat.\nUse the `$view` command to view all items in a hat.\nUse the `$pick` command to pick an item from a hat.\nUse the `$pop` command to pick and remove an item from a hat.\nUse the `$remove` command to remove an item from a hat.\nUse the `$clear` command to remove all items from a hat.\nUse the `$set_default` command to set a default hat to use for all Hat commands within a given channel."
"Are you a fan of Magic: the Gathering? Use the `$card` command to retrieve an image of any MtG card."
"Looking for some light-hearted fun? Use the `$comic` command to retrieve a random comic from many popular comic strips."
"Not sure what a word means? Use the `$define` command to retrieve the definition for a given word."
"You can use the `$image` command to search the web for pictures."
"You can use the `$video` command to search the web for videos."
"You can use the `$search` command to search the web for related webpages."
"Curious what the weather is around the world? Use the `$weather` command to retrieve the current weather for a given location."
"You can use the `$wiki` command to search Wikipedia for related articles."
"Love *xkcd*? Use the `$xkcd` command to retrieve *xkcd* comics."
"Struggling to make a choice? Use the `$choice` command to chose one item from a given list."
"Looking to learn something new? Try using the `$fact` command to recieve a random fun fact."
"You can use the `$flip` command to flip one or more coins."
"Need a random number? Use the `$number` command to recieve a random number within a given range."
"Looking to play the odds? Use the `$roll` command to roll one or more dice."
"Use the `$shuffle` command to randomly order a given list."
"Did you know you can upvote and downvote words and phrases? Simply append \"++\" to a word to upvote it, or append \"--\" to a word to downvote it. For example, sending the message: \"I love coffee++ but I hate tea--\" will add one upvote for \"coffee\" and one downvote for \"tea\". To upvote/downvote a multi-word item, simply enclose the item in parenthesis. For example, sending the message: \"I do not like (green eggs and ham)--\" will add one downvote for \"green eggs and ham\".\nUse the `$show` command to view the total score for a given word/phrase.\nUse the `$bot` command to view the lowest rated items.\nUse the `$top` command to view the highest rated items."
"Curious to know more about how I work? Use the `$info` command to view some information about me, including a link to my open-source code."
"You can use the `$ping` command to determine whether I am currently online, as well as the round-trip response time."
"Need a QR code? You can use the `$qr` command to generate a QR code for any given string of text."
"Did you know I feature a suite of Unix-Like commands for working with text files?\nUse the `$ls` command to view all present text files.\nUse the `$cat` command to view the contents of a given text file.\nUse the `$tee` command to add a new line into a given text file.\nUse the `$grep` command to search for lines within a given text file.\nUse the `$rm` command to remove a given text file."
"Want a random line from one of your server's text files? Simply append the \"#\" character to the front of a text file's name, and I will send a random line from that file."
"You can specify how I reply to rude and/or nice messages using the `$tee` command.\nTo add additional responses to rude messages, perform the command: `$tee respond_rude Your response here`.\nTo add additional responses to nice messages, perform the command: `$tee respond_nice Your response here`.\n\nAdditionally, you can specify what phrases I consider rude and/or nice.\nTo add additional rude phrases, perform the command: `$tee rude Your phrase here`.\nTo add additional nice phrases, perform the command: `$tee nice Your phrase here`."
"You can specify how I refer to myself within LLM responses using the `$tee` command. To add additional self descriptors for me, perform the command: `$tee descriptor Your descriptor here`."
]