TIP_LIST = [
"To view all available commands, use the `$help` command.",
"Many of my commands feature command flags you can use to modify/extend the capabilities of a given command.\nFor example, when using the `$image` command, I will only return one image by default. However, by using the `-c` command flag you can specify how many images I return. Performing the command `$image -c 3 Jet Neptune` will return three images related to \"Jet Neptune\".\nTo view all command flags for a given command use the `$help` command with the given command as an argument.\nExample: `$help image`",
"Not sure what a command does? You can use the `$help` command to learn more about how a command works. Simply use a given command name as an argument with the `$help` command.\nExample: `$help daily` will show you how to use the `$daily` command.",
"You can modify my system context to adjust my personality. Each channel has a unique system context message, which means you can adjust my personality differently for each channel.\nUse `$view_context` to view my current system context message for this channel.\nUse `$set_context` to overwrite my current system context message with a new one.\nUse `$add_context` to add additional content to my current system context message.",
"Whenever you send a message that includes my name, I will generate and send a response using my LLM. If you would like to use the LLM to generate a response without using my name, you can use the `$prompt` command.",
"Are you sick of me replying to your messages without being prompted? Use the `$ignore` command to stop me from replying to your messages unless you prompt me. Additionally, you can use the `-c` command flag to prevent me from replying to any unprompted messages in a given channel.",
"Want to hear my voice? You can command me to join your voice channel using the `$join` command. Once inside of your voice channel, I will read aloud any LLM responses generated as well as any one-line respones generated using the \"#\" character. Once you've grown tired of me, simply use the `$leave` command and I will exit your voice channel. Alternatively, if I detect I am the only user within a voice channel, I will exit the channel myself.",
"Did you know I have text-to-speach capabilities? Simply use the `$say` command, and I will read aloud any message to your voice channel.",
"Is your channel dead? Want me to send a daily message to your channel? Use the `$daily` command to instruct me to send comics, facts, and more to your channel once a day.",
"Are you bored? Play a game of Wordle with me! Use the `$wordle` command to begin a new game.",
"Want help collecting and randomly chosing text-based items? Use my suite of \"Hat-based Collection\" commands.\nUse the `$list` command to view all active hats in this server.\nUse the `$add` command to add an item to a hat.\nUse the `$view` command to view all items in a hat.\nUse the `$pick` command to pick an item from a hat.\nUse the `$pop` command to pick and remove an item from a hat.\nUse the `$remove` command to remove an item from a hat.\nUse the `$clear` command to remove all items from a hat.\nUse the `$set_default` command to set a default hat to use for all Hat commands within a given channel.",
"Are you a fan of Magic: the Gathering? Use the `$card` command to retrieve an image of any MtG card.",
"Looking for some light-hearted fun? Use the `$comic` command to retrieve a random comic from many popular comic strips.",
"Not sure what a word means? Use the `$define` command to retrieve the definition for a given word.",
"You can use the `$image` command to search the web for pictures.",
"You can use the `$video` command to search the web for videos.",
"You can use the `$search` command to search the web for related webpages.",
"Curious what the weather is around the world? Use the `$weather` command to retrieve the current weather for a given location.",
"You can use the `$wiki` command to search Wikipedia for related articles.",
"Love *xkcd*? Use the `$xkcd` command to retrieve *xkcd* comics.",
"Struggling to make a choice? Use the `$choice` command to chose one item from a given list.",
"Looking to learn something new? Try using the `$fact` command to recieve a random fun fact.",
"You can use the `$flip` command to flip one or more coins.",
"Need a random number? Use the `$number` command to recieve a random number within a given range.",
"Looking to play the odds? Use the `$roll` command to roll one or more dice.",
"Use the `$shuffle` command to randomly order a given list.",
"Did you know you can upvote and downvote words and phrases? Simply append \"++\" to a word to upvote it, or append \"--\" to a word to downvote it. For example, sending the message: \"I love coffee++ but I hate tea--\" will add one upvote for \"coffee\" and one downvote for \"tea\". To upvote/downvote a multi-word item, simply enclose the item in parenthesis. For example, sending the message: \"I do not like (green eggs and ham)--\" will add one downvote for \"green eggs and ham\".\nUse the `$show` command to view the total score for a given word/phrase.\nUse the `$bot` command to view the lowest rated items.\nUse the `$top` command to view the highest rated items.",
"Curious to know more about how I work? Use the `$info` command to view some information about me, including a link to my open-source code.",
"You can use the `$ping` command to determine whether I am currently online, as well as the round-trip response time.",
"Need a QR code? You can use the `$qr` command to generate a QR code for any given string of text.",
"Did you know I feature a suite of Unix-Like commands for working with text files?\nUse the `$ls` command to view all present text files.\nUse the `$cat` command to view the contents of a given text file.\nUse the `$tee` command to add a new line into a given text file.\nUse the `$grep` command to search for lines within a given text file.\nUse the `$rm` command to remove a given text file.",
"Want a random line from one of your server's text files? Simply append the \"#\" character to the front of a text file's name, and I will send a random line from that file.",
"You can specify how I reply to rude and/or nice messages using the `$tee` command.\nTo add additional responses to rude messages, perform the command: `$tee respond_rude Your response here`.\nTo add additional responses to nice messages, perform the command: `$tee respond_nice Your response here`.\n\nAdditionally, you can specify what phrases I consider rude and/or nice.\nTo add additional rude phrases, perform the command: `$tee rude Your phrase here`.\nTo add additional nice phrases, perform the command: `$tee nice Your phrase here`.",
"You can specify how I refer to myself within LLM responses using the `$tee` command. To add additional self descriptors for me, perform the command: `$tee descriptor Your descriptor here`.",
"When using my text-to-speach capabilities, you can specify an alternate voice for me to use. While using the `$say` command, use the `-v` command flag to specify which voice I should use. For example, using the command: `$say -v sage I sound like \"Sage\"` will cause me to use the voice `Sage` while reading your message. Use `$help say` to view a list of available voices.",
"When using my text-to-speach capabilities, you can specify the speed at which I read your message aloud. While using the `$say` command, use the `-s` command flag to specify what playback speed I should use. For example, using the command: `$say -s 0.5 I sound slow` will cause me to say the message at half speed.",
"For many commands that feature more than one command flag, you can use multiple command flags within the same command. For example, using the command: `$say -v sage -s 0.5 I sound like \"Sage\", but slow.` will cause me to read the message with the `Sage` voice at half speed.",
"Some of my commands have \"aliases\" you can use to invoke the command in addition to the official command name. For example, you can use the command `$chat` to invoke the `$prompt` command.",
"You can use the command `$daily -t` to trigger an immediate retreival of a daily item.",
"Want to view random Magic: the Gathering card? Use the command `$card -r`.",
"Want to view a random Wikipedia article? Use the command `$wiki -r`.",
"You can retrieve all images from a Wikipedia article using the `-i` flag. For example, using the command: `$wiki -i Alex Stein` will retrieve all images on the article for Alex Stein.",
"You can flip multiple coins at the same time with the `$flip` command by including an integer argument with the command. For example, using the command: `$flip 3` will flip three coins.",
"Using the `-m` command flag in with the `$roll` command will allow you to roll mutliple dice combinations simultaneously. For example, using the command: `$roll -m 4d20, 6d9` will roll four 20-sided dice and six 9-sided dice.",
"There are hidden commands. Can you find any of them?",
"Just like Ken Thompson's original program, the `$grep` command supports regular expressions.",
"Did you accidentally delete a file you didn't mean to with `$rm`? Don't fear, I backup all files nightly. Contact my developer, Vertical Bar, should you need to restore a deleted file.",
"Stuck in a game of `$wordle`? Use the command `$world -q` to quit an ongoing game.",
"Am I still acting too much like myself after using the `$set_context` command? By default, the command will simply add on to my default system context message. You can completely overwrite my system context message by using the `-o` command flag.",
"I have a small chance to reply to most messages sent in the server, even if you didn't request me to do so directly. However, if I determine my generated response isn't helpful, I will not send it. So, you may sometimes see me typing a message that is never sent.",
"Daily messages configured with the `$daily` command are sent at a weighted-random time in the day. Messages are more likely to be sent at times closer to noon Eastern Time, but can be sent anytime from 01:00-23:59.",
"Have a feature request for me? Contact my developer, Vertical Bar, to request implementation of additional features.",
"I can generate images from a given prompt with the `$generate` command.\nExample: `$generate Donald Trump as a Minecraft mob`",
"When using my `$generate` command I will \"enhance\" your prompt by default, adding additional context to help deliver the best image possible. To generate an image just using your raw prompt, use the `-p` command flag.\nExample: `$generate -p a chicken riding a cat`",
]
