activities = [
        "Listening for $help",
        "Waiting for someone to say Karn",
        "Listening for # symbols",
        "Awaiting a $ command",
        "Awaiting a / command",
        "Walking across Planes",
        "Leading New Phyrexia",
        "Inheriting the spark of Urza",
        "Inheriting the spark of Venser",
        "Sacrificing my spark",
        "Controlling all five colors of mana",
        "Experiencing pain and feelings",
        "Refusing to take pragmatic action",
        "Creating artifacts and automotons",
        "Touching Ral's goggles",
        "Deconstructing technology",
        "Using Urza's time machine",
        "Saving Jhoira",
        "Destroying the Tolarian Academy",
        "Rebuilding Tolaria",
        "Rescuing Teferi",
        "Helping in the Mana Rig",
        "Joining the Weatherlight voyages",
        "Repeating the mantra \"Jhoira is my friend\"",
        "Caring for the Capashen bloodline",
        "Rescuing Gerrard Capashen",
        "Retreiving the Legacy",
        "Taking a vow of pacificsm",
        "Refusing to fight off my attackers",
        "Crushing an endless supply of Moggs",
        "Seeking the Legacy artifacts",
        "Confronting Tsabo Tavoc",
        "Killing Phyrexians",
        "Helping Gerrard kill Tavoc",
        "Guiding the Weatherlight",
        "Triggering the Weatherlight's final evolution",
        "Creating Argentum",
        "Sending probes to monitor Dominaria",
        "Looking out upon the worlds",
        "Wandering the multiverse",
        "Sending dreams to Glissa",
        "Returning to Dominaria",
        "Sealing the time rifts",
        "Traveling back in time",
        "Helping the Gatewatch",
        "Traveling with the Gatewatch",
        "Fighting against the Eternals of Bolas' Dreadhorde",
        "Going through Bolas' Planar Bridge",
        "Joining the Gatewatch",
        "Searching the Caves of Koilos",
        "Attending a peace summit",
        "Hiding the Sylex",
        "Fighting off waves of Phyrexians",
        "Traveling to Shiv",
        "Returning to Elesh Norn",
        "Witenssing the return of Elspeth",
        "Creating an improvised body",
        "Breaking my pacifist vows",
        "Executing Elesh Norn",
]
