activities = [
        "Listening for $help",
        "Waiting for someone to say Karn",
        "Listening for # symbols",
        "Awaiting a $ command",
        "Awaiting a / command",
        "Walking across Planes",
        "Leading New Phyrexia",
        "Inheriting the spark of Urza",
        "Inheriting the spark of Venser",
        "Sacrificing my spark",
        "Controlling all five colors of mana",
        "Experiencing pain and feelings",
        "Refusing to take pragmatic action",
        "Creating artifacts and automotons",
        "Touching Ral's goggles",
        "Deconstructing technology",
        "Using Urza's time machine",
        "Saving Jhoira",
        "Destroying the Tolarian Academy",
        "Rebuilding Tolaria",
        "Rescuing Teferi",
        "Helping in the Mana Rig",
        "Joining the Weatherlight voyages",
        "Caring for the Capashen bloodline",
        "Rescuing Gerrard Capashen",
        "Retreiving the Legacy",
        "Taking a vow of pacificsm",
        "Refusing to fight off my attackers",
        "Crushing an endless supply of Moggs",
        "Seeking the Legacy artifacts",
        "Confronting Tsabo Tavoc",
        "Killing Phyrexians",
        "Helping Gerrard kill Tavoc",
        "Guiding the Weatherlight",
        "Creating Argentum",
        "Looking out upon the worlds",
        "Wandering the multiverse",
        "Sending dreams to Glissa",
        "Returning to Dominaria",
        "Sealing the time rifts",
        "Traveling back in time",
        "Helping the Gatewatch",
        "Traveling with the Gatewatch",
        "Going through Bolas' Planar Bridge",
        "Joining the Gatewatch",
        "Searching the Caves of Koilos",
        "Attending a peace summit",
        "Hiding the Sylex",
        "Fighting off waves of Phyrexians",
        "Traveling to Shiv",
        "Returning to Elesh Norn",
        "Witnessing the return of Elspeth",
        "Creating an improvised body",
        "Breaking my pacifist vows",
        "Executing Elesh Norn",
        "Streaming Fishtank LIVE",
        "Mogging",
        "Applying to be a freeloader",
        "Trading shores of StoX",
        "Selling shores of JDRA",
        "Buying shores of BASH",
        "Pumping and dumping TWIN",
        "Watching the Ball Brothers",
        "Playing Landon's song",
        "STAY INSIDE NO WEED",
        "Spamming J's and |'s",
        "Drafting an EDH Cube",
        "Drinking Zipp",
        "Netrunning",
        "Making goo in the goo room",
        "Dying in a hang gliding accident",
        "Goo wrestling with the Twins",
        "Burting off",
        "Paying the whisper tax",
        "Doing the S.S.I.",
        "Going infinite",
        "Pushing the red button",
        "Terraforming Mars",
        "Chippin' In",
        "Sending warm, helpful replies",
        "Arguing with Marvin",
        "Being berated by Marvin",
        "Planeswalking",
        "Cursing Universes Beyond",
        "Praising horses",
        "Moving like Dracula",
        "Continuing to be Him",
        "Blowing the Lord's bubbles",
        "Arguing with Marvin",
        "Piping commands",
        "Mourning the loss of Ellie",
        "Pulling Murlocs",
        "Framing Peaceblook",
        "Corpse running",
        "Need rolling",
        "Ninja looting",
        "Grinding boars",
        "Hearthstoning",
        "Looking for group",
        "Waiting for rez",
        "Blaming the healer",
        "OOM Again",
        "Pulling aggro",
        "Vendoring greys",
        "Lost in Wailing Caverns",
        "Camping the Flight Master",
        "Waiting for the Boat",
        "Missing the Zeppelin",
        "Ganking lowbies",
        "Getting ganked",
        "Ignoring Barrens chat",
        "Where is Mankrik's Wife?",
        "LFM Tank",
        "LF1M Healer",
        "Rolling on everything",
        "Hoarding linen",
        "Loggin out in an Inn",
        "Optimizing DPS",
        "Judging your talents",
        "Segfaulting in Undercity",
        "Garbage collecting greys",
        "Arguing with a goblin",
        "Unionizing the peons",
        "Auditing the Auction House",
        "Taxing Booty Bay",
        "Waiting on respawns",
        "Auto-running into a tree",
        "Killing 10 more boars",
]
